spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartfarm?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smartfarm
    password: Smartfarm1234!

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 3311
  error:
    whitelabel:
      enabled: false