spring:
  datasource:
    url: jdbc:mysql://61.97.187.175:3306/smartfarm?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: smartfarm
    password: Smartfarm1234!

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 3309
  error:
    whitelabel:
      enabled: false
