spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_farm?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jyj10241103*

  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

tcp:
  server:
    port: 8082